import { Routes } from '@angular/router';
import { GameDetailComponent } from './components/pages/game-detail/game-detail.component';
import { SearchResultsComponent } from './components/pages/search-results/search-results.component';
import { TrendingGamesComponent } from './components/pages/home/trending-games/trending-games.component';
import { WishlistComponent } from './components/pages/wishlist/wishlist.component';
import { MainPageComponent } from './main-page/main-page.component';
import { CollectionStatusComponent } from './components/pages/collection-status/collection-status.component';
import { SettingsComponent } from './components/pages/settings/settings.component';
import { ProfileComponent } from './components/pages/profile/profile.component';
import { UserSearchResultsComponent } from './components/pages/user-search-results/user-search-results.component';
import { UserProfileComponent } from './components/pages/settings/user-profile/user-profile.component';
import { CustomListsComponent } from './components/pages/custom-lists/custom-lists.component';
import { CustomListDetailComponent } from './components/pages/custom-lists/custom-list-detail/custom-list-detail.component';
import { AppsComponent } from './components/footer/apps/apps.component';
import { SuggestionsComponent } from './components/footer/suggestions/suggestions.component';
import { HomeComponent } from './components/pages/home/home.component';
import { ForgotPasswordComponent } from './auth/forgot-password/forgot-password.component';
import { ResetPasswordComponent } from './auth/reset-password/reset-password.component';

export const routes: Routes = [
  { path: '', component: MainPageComponent },
  { path: 'home', component: HomeComponent },
  { path: 'trending', component: TrendingGamesComponent },
  { path: 'search/:query', component: SearchResultsComponent },
  { path: 'detail/:id', component: GameDetailComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'wishlist', component: WishlistComponent },
  { path: 'custom-lists', component: CustomListsComponent },
  { path: 'custom-lists/:id', component: CustomListDetailComponent },
  { path: 'wishlist:userId', component: WishlistComponent },
  { path: 'collection', component: CollectionStatusComponent },
  { path: 'settings', component: SettingsComponent },
  { path: 'users/search/:query', component: UserSearchResultsComponent },
  { path: 'user/:username', component: ProfileComponent },
  { path: 'apps', component: AppsComponent },
  { path: 'suggestions', component: SuggestionsComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'reset-password', component: ResetPasswordComponent },

  { path: '**', redirectTo: '' },
];
